/**
 * Episode Animator — turns an episode of images into a cohesive video.
 *
 * Pipeline: Gather → Analyze → Prompt → Animate → Stitch → Upload
 *
 * Controlled by a skill file (public/skills/episode-director.md) that
 * defines motion prompt rules, model selection, duration, transitions.
 * Swap the skill → change the production style.
 */

import { useEpisodeStore } from "./store";
import { useCanvasStore } from "@/lib/canvas/store";
import { useChatStore } from "@/lib/chat/store";
import type { Card } from "@/lib/canvas/types";

/**
 * Stitch multiple video URLs into one, preserving each video's embedded audio.
 *
 * Plays each video sequentially through a <video> element, captures both
 * video (via canvas) and audio (via AudioContext) into a MediaRecorder.
 * This preserves the per-clip audio generated by Seedance/Kling.
 */
async function stitchVideosWithAudio(
  videoUrls: string[],
  onProgress?: (pct: number) => void,
): Promise<string> {
  // Load all videos — MUST be muted for autoplay to work (browser policy).
  // Audio is captured via Web Audio API createMediaElementSource, which
  // still receives audio data even when the element is muted in HTML.
  const videos: HTMLVideoElement[] = [];
  for (const url of videoUrls) {
    const vid = document.createElement("video");
    vid.crossOrigin = "anonymous";
    vid.muted = true; // required for programmatic play()
    vid.playsInline = true;
    vid.preload = "auto";
    vid.src = url;
    await new Promise<void>((resolve, reject) => {
      vid.onloadeddata = () => resolve();
      vid.onerror = () => reject(new Error(`Failed to load: ${url.slice(0, 60)}`));
      // Timeout fallback — some CDNs are slow
      setTimeout(() => resolve(), 15000);
    });
    videos.push(vid);
  }

  const w = videos[0].videoWidth || 1280;
  const h = videos[0].videoHeight || 720;

  // Canvas for video frames
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d")!;
  const canvasStream = canvas.captureStream(30);

  // Audio: capture from each video element via AudioContext
  const audioCtx = new AudioContext();
  const audioDest = audioCtx.createMediaStreamDestination();

  // Combined stream (video from canvas + audio from destination)
  const combined = new MediaStream([
    ...canvasStream.getVideoTracks(),
    ...audioDest.stream.getAudioTracks(),
  ]);

  const chunks: Blob[] = [];
  const recorder = new MediaRecorder(combined, {
    mimeType: MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")
      ? "video/webm;codecs=vp9,opus" : "video/webm",
    videoBitsPerSecond: 4_000_000,
  });
  recorder.ondataavailable = (e) => { if (e.data.size > 0) chunks.push(e.data); };

  return new Promise<string>((resolve, reject) => {
    recorder.onstop = () => {
      const blob = new Blob(chunks, { type: "video/webm" });
      audioCtx.close();
      if (blob.size < 1000) {
        reject(new Error(`Stitching produced empty video (${blob.size}B). Videos may have failed to load.`));
        return;
      }
      resolve(URL.createObjectURL(blob));
    };
    recorder.onerror = () => reject(new Error("Recording failed"));
    recorder.start(100);

    let currentIdx = 0;
    let totalPlayed = 0;
    const totalDuration = videos.reduce((s, v) => s + (v.duration || 5), 0);

    let currentSource: MediaElementAudioSourceNode | null = null;

    function playNext() {
      if (currentIdx >= videos.length) {
        recorder.stop();
        onProgress?.(1);
        return;
      }

      const vid = videos[currentIdx];

      // Connect audio: createMediaElementSource routes the element's audio
      // through the Web Audio API instead of to speakers. Once connected,
      // unmute the element so audio data flows through the source node.
      if (currentSource) { try { currentSource.disconnect(); } catch {} }
      try {
        currentSource = audioCtx.createMediaElementSource(vid);
        currentSource.connect(audioDest);
        vid.muted = false; // unmute AFTER routing to AudioContext (not to speakers)
      } catch {
        // Already created source for this element — just unmute
        vid.muted = false;
        currentSource = null;
      }

      vid.currentTime = 0;
      vid.play().catch(() => {
        // If unmuted play fails (autoplay policy), retry muted (no audio but video works)
        vid.muted = true;
        vid.play().catch(() => {});
      });

      // Draw frames
      const drawFrame = () => {
        if (vid.ended || vid.paused) return;
        ctx.drawImage(vid, 0, 0, w, h);
        totalPlayed = videos.slice(0, currentIdx).reduce((s, v) => s + (v.duration || 5), 0) + vid.currentTime;
        onProgress?.(totalPlayed / totalDuration);
        requestAnimationFrame(drawFrame);
      };
      requestAnimationFrame(drawFrame);

      vid.onended = () => {
        currentIdx++;
        playNext();
      };
    }

    playNext();
  });
}

export interface AnimateEpisodeOptions {
  episodeId: string;
  /** "per-clip" = animate each card separately then stitch. "multi-keyframe" = future. */
  approach?: "per-clip" | "multi-keyframe";
  /** Model override (default: from skill analysis) */
  model?: string;
  /** Music card ID to mix into final video */
  musicCardId?: string;
  /** "cinematic" | "fast" | custom skill name */
  style?: string;
}

export interface AnimateEpisodeResult {
  videoUrl: string;
  duration: number;
  clipCount: number;
  model: string;
  cardId: string;
}

/** Detect content type from a card for duration selection. */
function detectContentType(card: Card): string {
  const prompt = (card.prompt || card.title || "").toLowerCase();
  if (/title|text|logo|brand|intro|outro/.test(prompt)) return "title";
  if (/landscape|panorama|wide|establishing|aerial|skyline/.test(prompt)) return "establishing";
  if (/person|portrait|face|character|woman|man|girl|boy/.test(prompt)) return "character";
  if (/action|fight|run|chase|explod|battle|fast/.test(prompt)) return "action";
  if (/detail|close.up|macro|texture/.test(prompt)) return "detail";
  if (/emotion|dramatic|climax|epic|breathtaking/.test(prompt)) return "emotional";
  return "establishing"; // default
}

/** Get duration for a content type (from skill rules). */
function getDuration(contentType: string): number {
  const map: Record<string, number> = {
    title: 5, establishing: 10, character: 8,
    action: 7, detail: 6, emotional: 12,
  };
  return map[contentType] || 10;
}

/** Build motion prompt for a card. */
function buildMotionPrompt(card: Card, cohesionPrefix: string, contentType: string): string {
  const motionMap: Record<string, string> = {
    title: "subtle zoom in, elegant reveal",
    establishing: "slow cinematic pan, sweeping camera movement",
    character: "gentle push in, shallow depth of field, subtle movement",
    action: "dynamic tracking shot, energetic camera movement",
    detail: "slow drift, rack focus, intimate perspective",
    emotional: "slow dolly in, dramatic atmosphere, lingering moment",
  };

  const motion = motionMap[contentType] || "slow cinematic movement";
  const cardContext = card.prompt ? card.prompt.split(",").slice(0, 2).join(",").trim() : "";

  // Keep under 25 words: cohesion prefix + motion + brief context
  return `${cohesionPrefix}, ${motion}${cardContext ? `, ${cardContext}` : ""}`.slice(0, 200);
}

/** Select model based on style. */
function selectModel(style?: string): string {
  if (style === "fast") return "seedance-i2v-fast";
  if (style === "cinematic" || style === "premium") return "seedance-i2v";
  return "seedance-i2v"; // default
}

/**
 * Animate an entire episode into one cohesive video.
 *
 * Steps:
 * 1. Gather image cards from episode in order
 * 2. Analyze first card for overall style (cohesion prefix)
 * 3. Build per-card motion prompts
 * 4. Animate all cards in parallel
 * 5. Stitch clips into final video with transitions
 * 6. Upload to GCS for persistence
 * 7. Add final video card to canvas, linked to episode
 */
export async function animateEpisode(opts: AnimateEpisodeOptions): Promise<AnimateEpisodeResult | null> {
  const say = useChatStore.getState().addMessage;
  const update = useChatStore.getState().updateMessage;

  const store = useEpisodeStore.getState();
  const episode = store.getEpisode(opts.episodeId);
  if (!episode) { say("Episode not found.", "system"); return null; }

  const canvas = useCanvasStore.getState();
  const imageCards = episode.cardIds
    .map((id) => canvas.cards.find((c) => c.id === id))
    .filter((c): c is Card => !!c && c.type === "image" && !!c.url);

  if (imageCards.length === 0) { say("No images in this episode to animate.", "system"); return null; }

  const model = opts.model || selectModel(opts.style);
  const progressMsg = say(`Animating "${episode.name}" — ${imageCards.length} cards with ${model}...`, "system");

  // Step 1: Analyze first card for cohesion prefix
  let cohesionPrefix = "cinematic, dramatic lighting";
  try {
    const { analyzeImage } = await import("@/lib/tools/image-analysis");
    const analysis = await analyzeImage(imageCards[0].url!);
    if (analysis.ok) {
      cohesionPrefix = [
        analysis.analysis.style,
        analysis.analysis.palette ? `palette: ${analysis.analysis.palette}` : "",
        analysis.analysis.mood || "",
      ].filter(Boolean).join(", ");
      update(progressMsg.id, `Analyzing "${episode.name}" — style: ${analysis.analysis.style}`);
    }
  } catch {
    // Use default cohesion prefix
  }

  // Step 2: Build animation steps
  const steps = imageCards.map((card) => {
    const contentType = detectContentType(card);
    const duration = getDuration(contentType);
    const prompt = buildMotionPrompt(card, cohesionPrefix, contentType);
    return {
      action: "animate" as const,
      source_url: card.url!,
      prompt,
      duration,
      model_override: model,
    };
  });

  update(progressMsg.id, `Animating "${episode.name}" — ${steps.length} clips in parallel...`);

  // Step 3: Animate all in parallel via create_media
  // create_media creates BOTH image cards (keyframes) and video cards (clips).
  // We need to collect only the VIDEO URLs from the results.
  let clipUrls: string[] = [];
  try {
    const { executeTool } = await import("@/lib/tools/registry");
    const result = await executeTool("create_media", { steps });
    const data = result?.data as { results?: Array<{ refId?: string; url?: string }> } | undefined;
    // Filter to video results only (refIds from animate steps contain "vid" or the URLs are video)
    const allResults = data?.results || [];
    clipUrls = allResults
      .map((r) => r.url)
      .filter((u): u is string => !!u && !u.endsWith(".jpg") && !u.endsWith(".png"));

    // If all URLs look like videos (fal CDN doesn't always have extensions), take all
    if (clipUrls.length === 0) {
      clipUrls = allResults.map((r) => r.url).filter((u): u is string => !!u);
    }
  } catch (e) {
    update(progressMsg.id, `Animation failed: ${(e as Error).message?.slice(0, 80)}`);
    return null;
  }

  if (clipUrls.length === 0) {
    update(progressMsg.id, `No clips generated. Check model availability.`);
    return null;
  }

  update(progressMsg.id, `Stitching ${clipUrls.length} video clips...`);

  // Step 4: Stitch clips using mixMedia (preserves embedded audio from each clip)
  // mixMedia plays videos sequentially through <video> elements, capturing both
  // video frames AND audio. renderProject would lose audio because it draws to
  // canvas (visual only). Seedance generates audio per clip — mixMedia keeps it.
  let finalUrl: string;
  let totalDuration: number;
  try {
    const { mixMedia } = await import("@livepeer/creative-kit");

    // If user provided a music card, use it as the audio track.
    // Otherwise, let each clip's embedded audio play through.
    const musicUrl = opts.musicCardId
      ? canvas.cards.find((c) => c.id === opts.musicCardId)?.url
      : undefined;

    // mixMedia requires at least one audio URL. If no music card,
    // create a silent audio placeholder (the video clips already have audio).
    // Actually mixMedia needs audioUrls — if we pass the video URLs as both
    // video and audio, the video elements play their own audio.
    // But mixMedia's architecture separates video and audio tracks.
    // The simplest approach: use mixMedia with video URLs only if there's
    // external music, otherwise use a simpler direct stitch.
    if (musicUrl) {
      // External music track — mix clips + music
      finalUrl = await mixMedia({
        videoUrls: clipUrls,
        audioUrls: [musicUrl],
        onProgress: (pct) => update(progressMsg.id, `Stitching... ${Math.round(pct * 100)}%`),
      });
    } else {
      // No external music — stitch clips with their embedded audio.
      // Use MediaRecorder to concatenate video elements sequentially,
      // capturing both video and audio tracks from each <video> element.
      finalUrl = await stitchVideosWithAudio(clipUrls, (pct) => {
        update(progressMsg.id, `Stitching... ${Math.round(pct * 100)}%`);
      });
    }

    // Estimate duration from clip count * average duration
    totalDuration = steps.reduce((sum, s) => sum + s.duration, 0);

    // Upload to GCS for persistence
    try {
      const blob = await fetch(finalUrl).then((r) => r.blob());
      const reader = new FileReader();
      const dataUrl = await new Promise<string>((r) => { reader.onload = () => r(reader.result as string); reader.readAsDataURL(blob); });
      const resp = await fetch("/api/upload", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ dataUrl, fileName: `${episode.name}-video.webm` }) });
      if (resp.ok) { const d = await resp.json(); if (d.url) finalUrl = d.url; }
    } catch { /* keep blob URL */ }
  } catch (e) {
    update(progressMsg.id, `Stitching failed: ${(e as Error).message?.slice(0, 80)}`);
    return null;
  }

  // Step 5: Add final video card to canvas
  const refId = `ep-video-${Date.now()}`;
  const videoCard = useCanvasStore.getState().addCard({
    type: "video",
    title: `${episode.name} — ${clipUrls.length} clips (${totalDuration.toFixed(0)}s)`,
    refId,
    url: finalUrl,
  });

  // Link to source cards
  for (const card of imageCards) {
    useCanvasStore.getState().addEdge(card.refId, refId, { action: "episode-animate" });
  }

  update(progressMsg.id,
    `"${episode.name}" animated — ${clipUrls.length} clips, ${totalDuration.toFixed(1)}s video. Card: ${refId}`
  );

  // Auto-download
  const a = document.createElement("a"); a.href = finalUrl; a.download = `${episode.name}-video.webm`; a.click();

  return {
    videoUrl: finalUrl,
    duration: totalDuration,
    clipCount: clipUrls.length,
    model,
    cardId: videoCard.id,
  };
}
