import type { StreamRecipe, PipelineInfo } from "./types";
import {
  buildSimpleGraph,
  buildTextOnlyGraph,
  buildPreprocessorGraph,
  buildPostprocessorGraph,
} from "./graph-builder";

/** Known pipelines with their capabilities and defaults. */
export const KNOWN_PIPELINES: PipelineInfo[] = [
  {
    id: "longlive",
    name: "LongLive (CausalWan 1.3B)",
    vram_gb: 20,
    capabilities: ["lora", "vace", "prompt-travel", "kv-cache"],
    default_kv_cache: 1.0,
    default_fps: null,
  },
  {
    id: "ltx2",
    name: "LTX 2.3",
    vram_gb: 20,
    capabilities: ["prompt-travel", "kv-cache", "native-fps"],
    default_kv_cache: 0.3,
    default_fps: 24,
  },
  {
    id: "krea_realtime_video",
    name: "Krea Realtime Video (Wan2.1 14B)",
    vram_gb: 32,
    capabilities: ["lora", "vace", "prompt-travel", "kv-cache"],
    default_kv_cache: 1.0,
    default_fps: null,
  },
  {
    id: "memflow",
    name: "MemFlow (Kling + Memory Bank)",
    vram_gb: 20,
    capabilities: ["vace", "prompt-travel", "kv-cache", "memory-bank"],
    default_kv_cache: 1.0,
    default_fps: null,
  },
  {
    id: "video_depth_anything",
    name: "Video Depth Anything",
    vram_gb: 1,
    capabilities: ["preprocessor", "depth"],
    default_kv_cache: 0,
    default_fps: null,
  },
  {
    id: "scribble",
    name: "Scribble Contour",
    vram_gb: 1,
    capabilities: ["preprocessor", "edge-detection"],
    default_kv_cache: 0,
    default_fps: null,
  },
  {
    id: "rife",
    name: "RIFE Frame Interpolation",
    vram_gb: 1,
    capabilities: ["postprocessor", "interpolation"],
    default_kv_cache: 0,
    default_fps: null,
  },
];

/** Built-in stream recipes. */
export const BUILTIN_RECIPES: StreamRecipe[] = [
  {
    id: "classic",
    name: "Classic (LongLive)",
    description: "Default recipe. Stable prompt traveling with LoRA and VACE support.",
    pipeline: "longlive",
    graph: buildSimpleGraph("longlive"),
    defaults: { kv_cache_attention_bias: 0.5, denoising_step_list: [1000, 750, 500, 250] },
    quality: "balanced",
    capabilities: ["lora", "vace", "prompt-travel"],
    needsInput: true,
  },
  {
    id: "ltx-responsive",
    name: "LTX Responsive (24fps)",
    description: "Fast prompt response at native 24fps. More fluid motion, quicker morphing.",
    pipeline: "ltx2",
    graph: buildSimpleGraph("ltx2"),
    defaults: { kv_cache_attention_bias: 0.3, denoising_step_list: [1000, 750, 500, 250], manage_cache: true },
    quality: "balanced",
    capabilities: ["prompt-travel", "native-fps"],
    needsInput: true,
  },
  {
    id: "ltx-smooth",
    name: "LTX Smooth (48fps)",
    description: "LTX 2.3 with RIFE frame interpolation for buttery smooth output.",
    pipeline: "ltx2",
    graph: buildPostprocessorGraph("ltx2", "rife"),
    defaults: { kv_cache_attention_bias: 0.3, denoising_step_list: [1000, 750, 500, 250], manage_cache: true },
    quality: "quality",
    capabilities: ["prompt-travel", "native-fps", "interpolation"],
    needsInput: true,
  },
  {
    id: "depth-lock",
    name: "Depth Lock",
    description: "Preserves depth structure of input. Great for architecture and landscapes.",
    pipeline: "longlive",
    graph: buildPreprocessorGraph("longlive", "video_depth_anything"),
    defaults: { kv_cache_attention_bias: 0.7, denoising_step_list: [1000, 750, 500, 250] },
    quality: "quality",
    capabilities: ["lora", "vace", "prompt-travel", "depth"],
    needsInput: true,
  },
  {
    id: "scribble-guide",
    name: "Scribble Guided",
    description: "Uses edge/contour extraction to guide generation. Good for cartoon and sketch styles.",
    pipeline: "longlive",
    graph: buildPreprocessorGraph("longlive", "scribble"),
    defaults: { kv_cache_attention_bias: 0.5, denoising_step_list: [1000, 750, 500, 250] },
    quality: "quality",
    capabilities: ["lora", "vace", "prompt-travel", "edge-guided"],
    needsInput: true,
  },
  {
    id: "interpolated",
    name: "Interpolated (2x frames)",
    description: "LongLive with RIFE postprocessor for smoother output at 2x framerate.",
    pipeline: "longlive",
    graph: buildPostprocessorGraph("longlive", "rife"),
    defaults: { kv_cache_attention_bias: 0.5, denoising_step_list: [1000, 750, 500, 250] },
    quality: "quality",
    capabilities: ["lora", "vace", "prompt-travel", "interpolation"],
    needsInput: true,
  },
  {
    id: "fast-preview",
    name: "Fast Preview",
    description: "Quick preview with fewer denoising steps. Lower quality but faster iteration.",
    pipeline: "longlive",
    graph: buildSimpleGraph("longlive"),
    defaults: { kv_cache_attention_bias: 0.5, denoising_step_list: [1000, 500] },
    quality: "fast",
    capabilities: ["lora", "vace", "prompt-travel"],
    needsInput: true,
  },
  {
    id: "krea-hq",
    name: "Krea HQ (14B model)",
    description: "Highest visual fidelity using the 14B Wan2.1 model. Slower but stunning quality.",
    pipeline: "krea_realtime_video",
    graph: buildSimpleGraph("krea_realtime_video"),
    defaults: { kv_cache_attention_bias: 0.6, denoising_step_list: [1000, 750, 500, 250] },
    quality: "quality",
    capabilities: ["lora", "vace", "prompt-travel"],
    needsInput: true,
  },
  {
    id: "memflow-consistent",
    name: "MemFlow Consistent",
    description: "Best temporal consistency via memory bank. Ideal for persistent characters.",
    pipeline: "memflow",
    graph: buildSimpleGraph("memflow"),
    defaults: { kv_cache_attention_bias: 0.7, denoising_step_list: [1000, 750, 500, 250] },
    quality: "quality",
    capabilities: ["vace", "prompt-travel", "memory-bank"],
    needsInput: true,
  },
  {
    id: "text-only",
    name: "Text Only",
    description: "Pure text-to-video generation. No input source required.",
    pipeline: "longlive",
    graph: buildTextOnlyGraph("longlive"),
    defaults: { kv_cache_attention_bias: 0.5, denoising_step_list: [1000, 750, 500, 250] },
    quality: "balanced",
    capabilities: ["lora", "prompt-travel"],
    needsInput: false,
  },
];
